### ISSUE TITLE
Ctrl+J Doesn't Duplicate Layer

### ISSUE THREAD

**Issue by juanprl** [Diolinux/PhotoGIMP#22] opened 2020-07-10 17:41 UTC
In windows 10 with Gimp 2.10.20 and PhotoGimp 1.0 (10/07/20) when I use Ctrl+J doesnt make a Dupplicate layer as Photoshop. just a new empty layer . 

I don't know if gimp doesn't have an equivalent and that it's why it doesn't work or maybe are other reasons.

**Comment by fpedrosa1995** [comment] 2020-07-11 15:47
> In windows 10 with Gimp 2.10.20 and PhotoGimp 1.0 (10/07/20) when I use Ctrl+J doesnt make a Dupplicate layer as Photoshop. just a new empty layer .
> 
> I don't know if gimp doesn't have an equivalent and that it's why it doesn't work or maybe are other reasons.

Hi Juan, are u fine?

The keyboard shortcut do duplicate layers on GIMP (not PhotoGimp) is "**shift + control + d**" (see image below) , I think that you are a little bit confuse on shortcuts, can u see all shortcuts on "_Menu > Edit > Keyboard shortcuts_".
![image](https://user-images.githubusercontent.com/37274982/87227865-ef336680-c373-11ea-923f-b5321a89ecb1.png)

PS: **PhotoGimp has the same keyboard shortcut :D**
See ya!

**Comment by ironcore1** [comment] 2020-11-17 10:19
I think there is a little confusion with the report as I do believe there may be a bug here (but it could be with Gimp itself). Ctrl+J in photoshop creates a duplicate of the selected layer (as you have shown in the image above can also be accomplished by pressing **CTRL+SHIFT+D**) but there is an extra caveat to it which could be the bug.

In Photoshop if you select a layer with an image in it, then make a lasso selection (or something similar) and then press **Ctrl+J** it will only move the lasso selection into the new layer as a smart object and nothing else.

This can be accomplish in Gimp by making a Lasso selection in an area and right click **Select>Float** or they keyboard shortcut is **Shift+Ctrl+L** and then anchor it down within the layer. This will have then created a new layer with the previous selection within it.

It would be cool if PhotoGimp worked the same way.

https://youtu.be/wk960TDAyLU?t=292 - Here is a link of a video showing how Ctrl+J in photoshop works as it will do a better way of showing what happens with it.

P.S PhotoGimp is awesome and I'm so glad you made this. Keep up the great work.

**Comment by sudo-give-me-coffee** [comment] 2021-12-17 22:10
Is needed an script to do this, GIMP doesn't have a CTRL+J equivalent function natively

**Comment by gabrielalmir** [comment] 2024-02-14 23:51
Hello everyone,

It appears that the discussion around [issue/topic] has been inactive for a considerable period. As there haven't been recent contributions or activities, we've decided to close this issue.

We appreciate the time and insights shared by everyone during this discussion. If there are still relevant points to address or if you believe there's ongoing value in discussing this issue, please feel free to reopen it or start a new thread.

Thank you all for your contributions, and we look forward to your continued engagement on other issues.

Best regards,

**Closed by gabrielalmir** 2024-02-14 23:51 UTC
